<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AnalisisG extends Model
{
	protected $table = 'analisisg';
    protected $primaryKey = 'id_general';
    protected $fillable = [
        'id_general',
        'id_obra',
        'id_de_obra',
        'titulo_obra',
    	'temp_obra',
    	'epoca_obra',
    	'tipo_bien_cultu',
    	'tipo_obj_obra',
    	'lugar_proce_ori',
    	'lugar_proce_act',
    	'no_inv_obra',
    	'respon_intervencion',
    	'proyecto_obra',
    	'año_proyec_obra',
        'fecha_de_inicio',
        'foto'=>'required|image|mimes:jpeg,jpg,png',
        'alto',
        'ancho',	
        'profundidad',
        'diametro',
        'tecnica',
        'autor',
        'analisis',
        'Smuestra',
        'Snomenclatura',
        'Sinf_requerida',
        'Sdes_muestra',
        'Subicacion',
        'Smotivo',
        'Sresponsable',
        'Siden_muestra',
        'BPmuestra',
        'BPnomenclatura',
        'BPinf_requerida',
        'BPdes_muestra',
        'BPubicacion',
        'BPmotivo',
        'BPresponsable',
        'BPiden_muestra',
        'Emuestra',
        'Enomenclatura',
        'Einf_requerida',
        'Edes_muestra',
        'Eubicacion',
        'Emotivo',
        'Eresponsable',
        'Eiden_muestra',
        'REmuestra',
        'REnomenclatura',
        'REinf_requerida',
        'REdes_muestra',
        'REubicacion',
        'REmotivo',
        'REresponsable',
        'REiden_muestra',
        'BOLmuestra',
        'BOLnomenclatura',
        'BOLinf_requerida',
        'BOLdes_muestra',
        'BOLubicacion',
        'BOLmotivo',
        'BOLresponsable',
        'BOLiden_muestra',
        'LMmuestra',
        'LMnomenclatura',
        'LMinf_requerida',
        'LMdes_muestra',
        'LMubicacion',
        'LMmotivo',
        'LMresponsable',
        'LMiden_muestra',
        'Pmuestra',
        'Pnomenclatura',
        'Pinf_requerida',
        'Pdes_muestra',
        'Pubicacion',
        'Pmotivo',
        'Presponsable',
        'Piden_muestra',
        'Amuestra',
        'Anomenclatura',
        'Ainf_requerida',
        'Ades_muestra',
        'Aubicacion',
        'Amotivo',
        'Aresponsable',
        'Aiden_muestra',
        'Rmuestra',
        'Rnomenclatura',
        'Rinf_requerida',
        'Rdes_muestra',
        'Rubicacion',
        'Rmotivo',
        'Rresponsable',
        'Riden_muestra',
        'MASOmuestra',
        'MASOnomenclatura',
        'MASOinf_requerida',
        'MASOdes_muestra',
        'MASOubicacion',
        'MASOmotivo',
        'MASOresponsable',
        'MASOiden_muestra',
        'SALmuestra',
        'SALnomenclatura',
        'SALinf_requerida',
        'SALdes_muestra',
        'SALubicacion',
        'SALmotivo',
        'SALresponsable',
        'SALiden_muestra',
        'MAGREmuestra',
        'MAGREnomenclatura',
        'MAGREinf_requerida',
        'MAGREdes_muestra',
        'MAGREubicacion',
        'MAGREmotivo',
        'MAGREresponsable',
        'MAGREiden_muestra',
        'BIOmuestra',
        'BIOnomenclatura',
        'BIOinf_requerida',
        'BIOdes_muestra',
        'BIOubicacion',
        'BIOmotivo',
        'BIOresponsable',
        'BIOiden_muestra',
        'OTROmuestra',
        'OTROnomenclatura',
        'OTROinf_requerida',
        'OTROdes_muestra',
        'OTROubicacion',
        'OTROmotivo',
        'OTROresponsable',
        'OTROiden_muestra'
    ];

    public function scopeId($query, $id)
{
    if ($id)
        return $query->where('id_obra', 'LIKE', "%$id%");
}

    public function obra()
    {
    	return $this->belongsTo('App\Obras', 'id');
    }
    public function registro()
    {
        return $this->hasMany('App\AnalisisCientifico', 'id_gene');
    }
}
